apiVersion: apps/v1
kind: Deployment
metadata:
  name: archi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: archi
  template:
    metadata:
      labels:
        app: archi
    spec:
      containers:
        - image: ghcr.io/woozymasta/archimate-ci-image:5.7.0-1.0.6
          name: archi
          ports:
            - containerPort: 80
